package io.relayr.ble.service;

public interface ShortUUID {

    // General services & characteristics
    String SERVICE_BATTERY_LEVEL = "180f";
    String CHARACTERISTIC_BATTERY_LEVEL = "2a19";

    String SERVICE_DEVICE_INFO = "180a";
    String CHARACTERISTIC_FIRMWARE_VERSION = "2a26";
    String CHARACTERISTIC_HARDWARE_VERSION = "2a27";
    String CHARACTERISTIC_MANUFACTURER = "2a29";

    // Relayr related services
    String SERVICE_CONNECTED_TO_MASTER_MODULE = "2000";

    String SERVICE_ON_BOARDING = "2001";
    String CHARACTERISTIC_SENSOR_ID = "2010";
    String CHARACTERISTIC_PASS_KEY = "2018";
    String CHARACTERISTIC_ON_BOARDING_FLAG = "2019";

    String SERVICE_DIRECT_CONNECTION = "2002";
    // String CHARACTERISTIC_SENSOR_BEACON_FREQUENCY = "2011";
    String CHARACTERISTIC_SENSOR_FREQUENCY = "2012";
    String CHARACTERISTIC_SENSOR_LED_STATE = "2013";
    String CHARACTERISTIC_SENSOR_THRESHOLD = "2014";
    String CHARACTERISTIC_SENSOR_CONFIGURATION = "2015";
    String CHARACTERISTIC_SENSOR_DATA = "2016";
    String CHARACTERISTIC_SENSOR_SEND_COMMAND = "2017";

    String DESCRIPTOR_DATA_NOTIFICATIONS = "2902";

    //New onboarding
    String SERVICE_NEW_ON_BOARDING = "1900";
    String CHARACTERISTIC_WIFI_SSID = "2400";
    String CHARACTERISTIC_WIFI_PASSWORD = "2401";
    String CHARACTERISTIC_MQTT_HOST = "2402";
    String CHARACTERISTIC_MQTT_USER = "2403";
    String CHARACTERISTIC_MQTT_PASSWORD = "2404";
    String CHARACTERISTIC_MQTT_CLIENT_ID = "2405";
    String CHARACTERISTIC_MQTT_TOPIC = "2406";
    String CHARACTERISTIC_COMMIT = "2407";
    String CHARACTERISTIC_STATUS = "2408";
}
